# -*- coding: utf-8 -*-

faecher = {
    "AA"  : "Analysis und Lineare Algebra",
    "AD"  : "Algorithmen und Datenstrukturen",
    "AF"  : "Automatentheorie und Formale Sprachen",
    "AI"  : "Architektur von Informationssystemen",
    "AW"  : "Anwendungen",
    "BS"  : "Betriebssysteme",
    "BW"  : "Betriebswirtschaftslehre",
    "CE"  : "Computer Engineering",
    "CI"  : "Compiler und Interpreter",
    "DB"  : "Datenbanken",
    "DT"  : "Digitaltechnik",
    "GE"  : "Grundlagen Elektrotechnik",
    "GI"  : "Grundlagen der Informatik",
    "GS"  : "Grundlagen Systemnahes Programmieren",
    "GT"  : "Grundlagen Technische Informatik",
    "GKA" : "Graphentheoretische Konzepte und Algorithmen",
    "IS"  : "Intelligente Systeme",
    "LB"  : "Logik und Berechenbarkeit",
    "MA"  : "Mathematik",
    "MG"  : "Mathematische Grundlagen",
    "MI"  : "Modellierung von Informationssystemen",
    "MT"  : "Modellierung Technischer Systeme",
    "NS"  : "Numerik und Stochastik",
    "PJ"  : "Projekt",
    "PL"  : "Prozesslenkung",
    "PR"  : "Programmieren",
    "PRG" : "Grundlagen Programmieren",
    "RMP" : "Rechnerstrukturen und Maschinennahe Programmierung",
    "RN"  : "Rechnernetze",
    "RS"  : "Rechnerstrukturen",
    "SE"  : "Software Engineering",
    "SP"  : "Sprachen",
    "SY"  : "System- und Echtzeitprogrammierung",
    "TH"  : "Theoretische Informatik",
    "TSE" : "Team Studien Einstieg",
    "TT"  : "Technik und Technologie",
    "UO"  : "Unternehmensorientierung",
    "VS"  : "Verteilte Systeme",
}

